services:
  database:
    image: postgres
    container_name: projetoPsoft7_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=projetoPsoft7_db
    volumes:
      - pgdata:/data/postgres
    networks:
      - pitsa-network-bridge

  api:
    image: brunorramos22/pitsa:1.1
    container_name: PitsA-API
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/projetoPsoft7_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - pitsa-network-bridge
    ports:
      - 8080:8080
    depends_on:
      - database

networks:
  pitsa-network-bridge:
    driver: bridge

volumes:
  pgdata:
   driver: local